### ISSUE TITLE
브렌치 분리

### ISSUE THREAD

**Issue by iwin2471** [gadget502/brix-frontend#9]
브렌치가 하나이니 어디서 어떻게 뭐가 들어갔는지 한눈에 안보임

**Comment by real0131** [comment]
https://danielkummer.github.io/git-flow-cheatsheet/index.ko_KR.html
http://woowabros.github.io/experience/2017/10/30/baemin-mobile-git-branch-strategy.html

git flow 써서 feature 나눌게
